name: Deploy to NS + Purge Cloudflare

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.git*'
      - '**/*.md'
      - '**/.DS_Store'
      - 'log/**'
      - '**/*.zip'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:    ${{ secrets.SFTP_HOST }}
          port:      ${{ secrets.SFTP_PORT }}        # e.g. 22
          username:  ${{ secrets.SFTP_USER }}
          password:  ${{ secrets.SFTP_PASS }}
          local_path: .
          remote_path: "${{ secrets.SFTP_REMOTE_PATH }}"   # e.g. "/htdocs"
          exclude: |
            .git*
            .github/**
            README.md
            log/**
            **/*.zip
          delete_remote_files: false

      - name: Purge Cloudflare cache
        run: |
          curl -sS -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'

      - name: Warm cache (optional)
        run: |
          curl -sS https://dreamwoodofficial.com/ -o /dev/null
          curl -sS https://www.dreamwoodofficial.com/ -o /dev/null
